package com.maxwell.contactmgr.model;

import javax.persistence.*;

/**
 * Created by greermp on 6/24/2017.
 * Contacts for our Hibernate configured database! :-O
 */

//Entity annotation will marl this class as one to persist to database.  By default, given their own table.
//    When detected, each contact object will be mapped to a row in the contact table of the database
//    Optional name element can be used to map them to a table.  By default the class name is used.
@Entity
public class Contact {
    @Id // Serves as entities Primary Key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //Automatically generated by hibernate.  Strategy to be used for generating new ids
    private int id;
    //Column annotation is not required.  Since we have the @Id annotation, all other fields will be automatically mapped to a column unless marked as transient
    //Again, can be used with a "name" field to name the column in the DB
    @Column
    private String firstname;
    @Column
    private String lastname;
    @Column
    private String email;
    @Column
    private Long phone;

    transient int notusedbyDB;

    public Contact() {}

    public Contact (ContactBuilder builder ) {
        this.firstname = builder.firstname;
        this.lastname = builder.lastname;
        this.email = builder.email;
        this.phone = builder.phone;
    }

    public Contact(int id, String firstname, String lastname, String email, Long phone) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.phone = phone;
    }

    @Override
    public String toString() {
        return "Contact{" +
                "id=" + id +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", email='" + email + '\'' +
                ", phone=" + phone +
                '}';
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getPhone() {
        return phone;
    }

    public void setPhone(Long phone) {
        this.phone = phone;
    }

    public static class ContactBuilder {
        private String firstname;
        private String lastname;
        private String email;
        private Long phone;

        public ContactBuilder(String firstName, String lastName) {
            this.firstname = firstName;
            this.lastname = lastName;
        }

        public ContactBuilder withEmail (String email) {
            this.email = email;
            return this;
        }

        public ContactBuilder withPhone (Long phone) {
            this.phone = phone;
            return this;
        }

        public Contact build() {
            return new Contact(this);
        }

    }
}
